SPREADSHEET_ID = 'SPREADSHEET ID HERE'
RANGE_NAME = 'SPREADSHEET RANGE HERE'
EMAIL = "ENTER YOUR EMAIL HERE"
PHONE_NUMBER = '1234567890'
TWILIO_ID = 'XXXXXXXXXXXXXXXXXXXX'
TWILIO_ACCOUNT_TOKEN = 'XXXXXXXXXXXXXXXXX'